version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - install
      - run:
          name: Build Docs
          command: yarn build
  lint:
    executor: node
    steps:
      - install
      - run:
          name: Lint Code
          command: yarn lint
  release:
    executor: node
    steps:
      - install
      - run:
          name: Semantic Release
          command: yarn semantic-release

workflows:
  version: 2
  check_and_release:
    jobs:
      - lint
      - build
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
            - build
